[phases.setup]
nixPkgs = ["nodejs", "google-chrome", "cacert"]

[phases.build]
cmds = ["npm install"]

[start]
# Esto le dice a la librería dónde está el Chrome que instaló Railway
cmd = "PUPPETEER_EXECUTABLE_PATH=$(which google-chrome-stable) node index.js"
